### ISSUE TITLE
blog作成

### ISSUE THREAD

**Issue by kimuray** [kimuray/day13#3]
@lasershow さん
blog作成をお願いします。

**Comment by lasershow** [comment]
@kimuray 承知しましたー

**Comment by lasershow** [comment]
@kimuray すいません　再度こちらのアカウントを招待して頂けますか

**Comment by kimuray** [comment]
@diveintocode をコラボレートしました。

**Comment by diveintocode** [comment]
@kimuray  こちらのアカウントで対応させていただきます
